import React from 'react';

interface ResultCardProps {
  content: string;
  onCopy: () => void;
  isCopied: boolean;
}

export const ResultCard: React.FC<ResultCardProps> = ({ content, onCopy, isCopied }) => {
  if (!content) return null;

  return (
    <div className="w-full mt-6 bg-gradient-to-br from-indigo-50 to-purple-50 border border-indigo-100 rounded-xl p-6 shadow-sm relative overflow-hidden group">
      <div className="absolute top-0 right-0 p-4 opacity-0 group-hover:opacity-100 transition-opacity">
        <button 
          onClick={onCopy}
          className="text-xs font-medium text-indigo-600 bg-white px-2 py-1 rounded shadow hover:bg-indigo-50 transition-colors"
        >
          {isCopied ? 'Copied!' : 'Copy'}
        </button>
      </div>
      <h3 className="text-sm font-semibold text-indigo-900 uppercase tracking-wider mb-2">Gemini Says:</h3>
      <p className="text-xl md:text-2xl text-gray-800 font-medium leading-relaxed">
        "{content}"
      </p>
      <div className="mt-4 flex items-center justify-end">
        <span className="text-xs text-indigo-400 font-medium">Generated by Gemini 2.5 Flash</span>
      </div>
    </div>
  );
};